[최현수] Add : product-list-view
wecode-bootcamp-korea/24-2nd-Overdos-backend pull request #2
Opened 2021-09-16 09:37 UTC by filola

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 전체 리스트 출력 및 유닛테스트 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-16 09:38 UTC, filola commented
![스크린샷 2021-09-16 오후 6 37 24](https://user-images.githubusercontent.com/45662443/133589048-c1156a21-6249-4d3c-b29b-e8d89bdec47f.png)
<img width="1438" alt="스크린샷 2021-09-16 오후 6 37 10" src="https://user-images.githubusercontent.com/45662443/133589066-79ecac05-8c55-48e7-a6b1-473b2716212c.png">

2021-09-17 01:42 UTC, S2-J1NG requested changes
유닛테스트 금방 작성하셨네요! 수고하셨습니다🙂
로직에 에러 추가하여 테스트에도 반영해주세요~!

2021-09-17 01:42 UTC, S2-J1NG commented on products/tests.py
> +        )
테스트 하는 데이터는 실제 들어가는 값과 유사하게 넣어주세요.
bulk create 보다 create로 작성해주세요!

2021-09-17 01:42 UTC, S2-J1NG commented on products/views.py
> +        return JsonResponse({"Result" : result}, status=200)
이미지가 없을 경우 발생할 수 있는 에러 잡아주세요

2021-09-17 07:54 UTC, filola commented on products/views.py
> +        return JsonResponse({"Result" : result}, status=200)
multiple error는 찾지 못하였습니다. Does not exists에러만 잡았습니다.

2021-09-17 07:54 UTC, filola commented on products/tests.py
> +        )
작성완료했습니다!

2021-09-17 08:21 UTC, S2-J1NG requested changes
유닛테스트는 성공, 실패, 예외 케이스에 대해 작성 해주세요
예외는 로직에서 `except` 처리한 부분이 발생할 수 있는 상황 만들어서 작성해주세요

2021-09-17 08:21 UTC, S2-J1NG commented on products/tests.py
> +    def test_productlistview_get_success(self):
`Image.DoesNotExist:` 에러 처리에 대한 유닛테스트 만들어주세요

2021-09-17 08:21 UTC, S2-J1NG commented on products/tests.py
> +    def test_product_detailview_success(self):
`Product.DoesNotExist` 에 대한 에러도 처리해주세요

2021-09-27 09:28 UTC, filola commented on products/tests.py
> +    def test_productlistview_get_success(self):
만들었습니다

2021-09-27 09:28 UTC, filola commented on products/tests.py
> +    def test_product_detailview_success(self):
처리하였습니다.

2021-09-27 09:30 UTC, filola commented
<img width="693" alt="스크린샷 2021-09-27 오후 6 29 52" src="https://user-images.githubusercontent.com/45662443/134882831-59e5ebae-c29a-4cb8-b7d2-de32cacc78b9.png">

2021-09-27 09:52 UTC, S2-J1NG requested changes

2021-09-27 09:52 UTC, S2-J1NG commented on products/tests.py
> +        Summary.objects.all().delete()
동일한 클래스에서 만들어지는 테스트 함수에 대해서 중복해서 setup과 teardown을 작성할 필요는 없습니다.
중복되는 데이터이므로 삭제해주세요

2021-09-28 01:53 UTC, filola commented on products/tests.py
> +        Summary.objects.all().delete()
수정했습니다.

2021-09-28 01:54 UTC, S2-J1NG approved these changes

2021-09-28 01:55 UTC, S2-J1NG commented
LGTM 🥳

2021-09-28 01:55 UTC, merged