[filling] 회원가입, 로그인, 카카오로그인 views 작성
wecode-bootcamp-korea/24-2nd-Overdos-backend pull request #3
Opened 2021-09-17 08:38 UTC by kohys92

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입, 로그인, 카카오로그인 views 작성 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [ ] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-09-17 09:08 UTC, S2-J1NG requested changes
model 수정은 브랜치 새로 생성해서 해주세요!

2021-09-17 09:08 UTC, ghost commented on users/views.py
> +            url = "https://kapi.kakao.com/v2/user/me"
`KAKAOURL = ` 변수의 상수화 해주세요!

2021-09-17 09:08 UTC, ghost commented on users/views.py
> +            token = jwt.encode({'id' : user.social_id}, SECRET_KEY, algorithm=ALGORITHM)
`social_id` 대신 user.id으로 작성해주세요!

2021-09-17 09:08 UTC, ghost commented on users/views.py
> +            }
불필요한 요소는 삭제해주세요!

2021-09-17 09:08 UTC, S2-J1NG commented on users/tests.py
> +
view 로직에서 DB에 저장된 비밀번호를 확인하기 때문에 setup에 bcrypt한 비밀번호를 추가하면 됩니다!
유닛테스트는 view에 있는 로직을 테스트 하기 때문에 view 어떻게 작성했는지 확인하면서 수정하면 됩니다

아래 예시 참고해서 수정해보세요!
```
def setup(self):
   hashed_password = bcrypt.hashpw("Abcd1111!".encode('utf-8'), bcrypt.gensalt())
   db_password         = hashed_password.decode('utf-8')

    user = User.objects.create(
            ...
            password = db_password
            )
```

2021-09-17 10:58 UTC, kohys92 commented on users/views.py
> +            url = "https://kapi.kakao.com/v2/user/me"
수정했습니다~

2021-09-17 11:02 UTC, kohys92 commented on users/views.py
> +            token = jwt.encode({'id' : user.social_id}, SECRET_KEY, algorithm=ALGORITHM)
수정했습니다~

2021-09-17 11:02 UTC, kohys92 commented on users/views.py
> +            }
삭제했습니다~

2021-09-23 15:51 UTC, kohys92 commented on users/tests.py
> +
예시 참고해서 회원가입, 로그인 유닛테스트 작성했습니다!

2021-09-27 01:31 UTC, S2-J1NG requested changes

2021-09-27 01:31 UTC, S2-J1NG commented on users/tests.py
> +
카카오 로그인 key 에러 유닛테스트 추가해주세요!

2021-09-27 03:01 UTC, kohys92 commented on users/tests.py
> +
추가했습니다! 리뷰 부탁드려요~

2021-09-27 06:14 UTC, S2-J1NG requested changes

2021-09-27 06:14 UTC, S2-J1NG commented on users/tests.py
> +
keyerror 가 나는 경우는 카카오 토큰으로 아무 정보도 못 받아 올 때 날 수 있겠죠?
아래 응답 참고해서 테스트 작성해주세요!
```
@patch('user.views.requests')
    def test_kakao_login_post_key_error(self, mocked_request):
        
        class MockedResponse:
            def json(self):
                return {
                        }
```

2021-09-28 01:34 UTC, S2-J1NG requested changes

2021-09-28 01:34 UTC, S2-J1NG commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_TOKEN'}, status = 401)
카카오 공식 문서에 보면 토큰 정보가 올바르지 않은 경우에 대해 설명되어 있습니다.
https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#get-token-info

따라서 요청을 할 때 토큰 정보가 올바르지 않으면, `json` 객체로 상세 정보를 받으며 유효하지 않은 토큰에 대해서는 -401이라는 코드 값을 받게 됩니다.
https://developers.kakao.com/docs/latest/ko/reference/rest-api-reference#response-code

두 문서 참고해서 코드로 정리를 하면 아래와 같은 형태가 되겠죠? 
```
account          = response.json()
if account.get('code') == -401:
                return JsonResponse({'message':'INVALID_TOKEN'}, status=401)
```
 view 수정 후 유닛테스트 부분도 수정해서 반영해주세요~!

2021-09-28 01:34 UTC, S2-J1NG commented on users/tests.py
> +        response = client.post('/users/kakaologin', content_type='application/json', **header)
view에서 코드 수정이 있었으므로 여기도 mock patch로 다시 데이터를 호출한 뒤 응답 값으로 {"code" : -401}을 넣어주고 테스트를 진행해야겠죠?

```
@patch('user.views.requests')
    def test_kakao_login_post_invaild_kakako_token(self, mocked_request):

        class MockedResponse:
            def json(self):
                return {
                        "code": -401
                        }

        mocked_request.get = MagicMock(return_value=MockedResponse())
        headers  = {'HTTP_Authorization': 'fake_token'}
```

2021-09-28 06:47 UTC, kohys92 commented on users/tests.py
> +        response = client.post('/users/kakaologin', content_type='application/json', **header)
참고해서 수정했습니다!

2021-09-28 06:48 UTC, kohys92 commented on users/views.py
> +                return JsonResponse({'message' : 'INVALID_TOKEN'}, status = 401)
views, 유닛테스트 둘 다 수정했습니다!

2021-09-28 07:25 UTC, S2-J1NG approved these changes

2021-09-28 07:25 UTC, S2-J1NG commented
LGTM 🥳 수고 하셨습니다!

2021-09-28 07:25 UTC, merged